version: '3'
services:
  app:
    container_name: "figapp-container"
    build:
      context: .
    volumes:
      - ./src:/usr/src
    command: sh -c "cd fig-app && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true